package com.xsyj.irrigation.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class WELL implements Serializable {
    private Long theser;

    private String stcd;

    private String deviceAd;

    private String wellNo;

    private String wellName;

    private String wellType;

    private String wellJd;

    private String wellWd;

    private String wellJs;

    private String wellJgkj;

    private String wellJgcl;

    private String wellJkgc;

    private String wellCskj;
    private String wellJsw;

    private BigDecimal wellGgmj;

    private String wellSbxh;

    private String wellYc;

    private String wellLy;

    private String wellGl;

    private Date wellJjsj;

    private String wellGgfs;

    private String wellGgdx;

    private String wellZbhj;

    private String wellDj;
    private String wellAddvcd;

    private String wellShenhe;
    
    private String userid;
    
    private String tapName;
    private String openMouth;
    private String isBindA;
    private String isBindB;

    public WELL() {
    }


    public WELL(Long theser, String stcd, String deviceAd, String wellNo, String wellName, String wellType, String wellJd, String wellWd, String wellJs, String wellJgkj, String wellJgcl, String wellJkgc, String wellCskj, String wellJsw, BigDecimal wellGgmj, String wellSbxh, String wellYc, String wellLy, String wellGl, Date wellJjsj, String wellGgfs, String wellGgdx, String wellZbhj, String wellDj, String wellAddvcd, String wellShenhe, String userid, String tapName, String openMouth, String isBindA, String isBindB) {
        this.theser = theser;
        this.stcd = stcd;
        this.deviceAd = deviceAd;
        this.wellNo = wellNo;
        this.wellName = wellName;
        this.wellType = wellType;
        this.wellJd = wellJd;
        this.wellWd = wellWd;
        this.wellJs = wellJs;
        this.wellJgkj = wellJgkj;
        this.wellJgcl = wellJgcl;
        this.wellJkgc = wellJkgc;
        this.wellCskj = wellCskj;
        this.wellJsw = wellJsw;
        this.wellGgmj = wellGgmj;
        this.wellSbxh = wellSbxh;
        this.wellYc = wellYc;
        this.wellLy = wellLy;
        this.wellGl = wellGl;
        this.wellJjsj = wellJjsj;
        this.wellGgfs = wellGgfs;
        this.wellGgdx = wellGgdx;
        this.wellZbhj = wellZbhj;
        this.wellDj = wellDj;
        this.wellAddvcd = wellAddvcd;
        this.wellShenhe = wellShenhe;
        this.userid = userid;
        this.tapName = tapName;
        this.openMouth = openMouth;
        this.isBindA = isBindA;
        this.isBindB = isBindB;
    }

    public String getIsBindA() {
		return isBindA;
	}

	public void setIsBindA(String isBindA) {
		this.isBindA = isBindA;
	}

	public String getIsBindB() {
		return isBindB;
	}

	public void setIsBindB(String isBindB) {
		this.isBindB = isBindB;
	}

	public String getTapName() {
		return tapName;
	}

	public void setTapName(String tapName) {
		this.tapName = tapName;
	}

	public String getOpenMouth() {
		return openMouth;
	}

	public void setOpenMouth(String openMouth) {
		this.openMouth = openMouth;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Long getTheser() {
        return theser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.theSer
     *
     * @param theser the value for B_WELL.theSer
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setTheser(Long theser) {
        this.theser = theser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.STCD
     *
     * @return the value of B_WELL.STCD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getStcd() {
        return stcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.STCD
     *
     * @param stcd the value for B_WELL.STCD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setStcd(String stcd) {
        this.stcd = stcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Device_AD
     *
     * @return the value of B_WELL.Device_AD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getDeviceAd() {
        return deviceAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Device_AD
     *
     * @param deviceAd the value for B_WELL.Device_AD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setDeviceAd(String deviceAd) {
        this.deviceAd = deviceAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_NO
     *
     * @return the value of B_WELL.Well_NO
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellNo() {
        return wellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_NO
     *
     * @param wellNo the value for B_WELL.Well_NO
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellNo(String wellNo) {
        this.wellNo = wellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_Name
     *
     * @return the value of B_WELL.Well_Name
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellName() {
        return wellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_Name
     *
     * @param wellName the value for B_WELL.Well_Name
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellName(String wellName) {
        this.wellName = wellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_Type
     *
     * @return the value of B_WELL.Well_Type
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellType() {
        return wellType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_Type
     *
     * @param wellType the value for B_WELL.Well_Type
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellType(String wellType) {
        this.wellType = wellType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JD
     *
     * @return the value of B_WELL.Well_JD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJd() {
        return wellJd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JD
     *
     * @param wellJd the value for B_WELL.Well_JD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJd(String wellJd) {
        this.wellJd = wellJd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_WD
     *
     * @return the value of B_WELL.Well_WD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellWd() {
        return wellWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_WD
     *
     * @param wellWd the value for B_WELL.Well_WD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellWd(String wellWd) {
        this.wellWd = wellWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JS
     *
     * @return the value of B_WELL.Well_JS
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJs() {
        return wellJs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JS
     *
     * @param wellJs the value for B_WELL.Well_JS
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJs(String wellJs) {
        this.wellJs = wellJs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JGKJ
     *
     * @return the value of B_WELL.Well_JGKJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJgkj() {
        return wellJgkj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JGKJ
     *
     * @param wellJgkj the value for B_WELL.Well_JGKJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJgkj(String wellJgkj) {
        this.wellJgkj = wellJgkj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JGCL
     *
     * @return the value of B_WELL.Well_JGCL
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJgcl() {
        return wellJgcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JGCL
     *
     * @param wellJgcl the value for B_WELL.Well_JGCL
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJgcl(String wellJgcl) {
        this.wellJgcl = wellJgcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JKGC
     *
     * @return the value of B_WELL.Well_JKGC
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJkgc() {
        return wellJkgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JKGC
     *
     * @param wellJkgc the value for B_WELL.Well_JKGC
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJkgc(String wellJkgc) {
        this.wellJkgc = wellJkgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_CSKJ
     *
     * @return the value of B_WELL.Well_CSKJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellCskj() {
        return wellCskj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_CSKJ
     *
     * @param wellCskj the value for B_WELL.Well_CSKJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellCskj(String wellCskj) {
        this.wellCskj = wellCskj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JSW
     *
     * @return the value of B_WELL.Well_JSW
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellJsw() {
        return wellJsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JSW
     *
     * @param wellJsw the value for B_WELL.Well_JSW
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJsw(String wellJsw) {
        this.wellJsw = wellJsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_GGMJ
     *
     * @return the value of B_WELL.Well_GGMJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public BigDecimal getWellGgmj() {
        return wellGgmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_GGMJ
     *
     * @param wellGgmj the value for B_WELL.Well_GGMJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellGgmj(BigDecimal wellGgmj) {
        this.wellGgmj = wellGgmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_SBXH
     *
     * @return the value of B_WELL.Well_SBXH
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellSbxh() {
        return wellSbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_SBXH
     *
     * @param wellSbxh the value for B_WELL.Well_SBXH
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellSbxh(String wellSbxh) {
        this.wellSbxh = wellSbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_YC
     *
     * @return the value of B_WELL.Well_YC
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellYc() {
        return wellYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_YC
     *
     * @param wellYc the value for B_WELL.Well_YC
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellYc(String wellYc) {
        this.wellYc = wellYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_LY
     *
     * @return the value of B_WELL.Well_LY
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellLy() {
        return wellLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_LY
     *
     * @param wellLy the value for B_WELL.Well_LY
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellLy(String wellLy) {
        this.wellLy = wellLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_GL
     *
     * @return the value of B_WELL.Well_GL
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellGl() {
        return wellGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_GL
     *
     * @param wellGl the value for B_WELL.Well_GL
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellGl(String wellGl) {
        this.wellGl = wellGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_JJSJ
     *
     * @return the value of B_WELL.Well_JJSJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public Date getWellJjsj() {
        return wellJjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_JJSJ
     *
     * @param wellJjsj the value for B_WELL.Well_JJSJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellJjsj(Date wellJjsj) {
        this.wellJjsj = wellJjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_GGFS
     *
     * @return the value of B_WELL.Well_GGFS
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellGgfs() {
        return wellGgfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_GGFS
     *
     * @param wellGgfs the value for B_WELL.Well_GGFS
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellGgfs(String wellGgfs) {
        this.wellGgfs = wellGgfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_GGDX
     *
     * @return the value of B_WELL.Well_GGDX
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellGgdx() {
        return wellGgdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_GGDX
     *
     * @param wellGgdx the value for B_WELL.Well_GGDX
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellGgdx(String wellGgdx) {
        this.wellGgdx = wellGgdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_ZBHJ
     *
     * @return the value of B_WELL.Well_ZBHJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellZbhj() {
        return wellZbhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_ZBHJ
     *
     * @param wellZbhj the value for B_WELL.Well_ZBHJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellZbhj(String wellZbhj) {
        this.wellZbhj = wellZbhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_DJ
     *
     * @return the value of B_WELL.Well_DJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellDj() {
        return wellDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_DJ
     *
     * @param wellDj the value for B_WELL.Well_DJ
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellDj(String wellDj) {
        this.wellDj = wellDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_ADDVCD
     *
     * @return the value of B_WELL.Well_ADDVCD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellAddvcd() {
        return wellAddvcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_ADDVCD
     *
     * @param wellAddvcd the value for B_WELL.Well_ADDVCD
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellAddvcd(String wellAddvcd) {
        this.wellAddvcd = wellAddvcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_WELL.Well_ShenHe
     *
     * @return the value of B_WELL.Well_ShenHe
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public String getWellShenhe() {
        return wellShenhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_WELL.Well_ShenHe
     *
     * @param wellShenhe the value for B_WELL.Well_ShenHe
     *
     * @mbggenerated Thu Jul 21 10:08:08 CST 2016
     */
    public void setWellShenhe(String wellShenhe) {
        this.wellShenhe = wellShenhe;
    }

    @Override
    public String toString() {
        return "WELL{" +
                "theser=" + theser +
                ", stcd='" + stcd + '\'' +
                ", deviceAd='" + deviceAd + '\'' +
                ", wellNo='" + wellNo + '\'' +
                ", wellName='" + wellName + '\'' +
                ", wellType='" + wellType + '\'' +
                ", wellJd='" + wellJd + '\'' +
                ", wellWd='" + wellWd + '\'' +
                ", wellJs='" + wellJs + '\'' +
                ", wellJgkj='" + wellJgkj + '\'' +
                ", wellJgcl='" + wellJgcl + '\'' +
                ", wellJkgc='" + wellJkgc + '\'' +
                ", wellCskj='" + wellCskj + '\'' +
                ", wellJsw='" + wellJsw + '\'' +
                ", wellGgmj=" + wellGgmj +
                ", wellSbxh='" + wellSbxh + '\'' +
                ", wellYc='" + wellYc + '\'' +
                ", wellLy='" + wellLy + '\'' +
                ", wellGl='" + wellGl + '\'' +
                ", wellJjsj=" + wellJjsj +
                ", wellGgfs='" + wellGgfs + '\'' +
                ", wellGgdx='" + wellGgdx + '\'' +
                ", wellZbhj='" + wellZbhj + '\'' +
                ", wellDj='" + wellDj + '\'' +
                ", wellAddvcd='" + wellAddvcd + '\'' +
                ", wellShenhe='" + wellShenhe + '\'' +
                ", userid='" + userid + '\'' +
                ", tapName='" + tapName + '\'' +
                ", openMouth='" + openMouth + '\'' +
                ", isBindA='" + isBindA + '\'' +
                ", isBindB='" + isBindB + '\'' +
                '}';
    }
}